language: android
dist: trusty
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - platform-tools-29.0.3
    # The BuildTools version used
    - build-tools-29.0.3
    # The SDK version used to compile
    - android-29
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    # Emulator image
    - sys-img-x86-android-29
# before_install:
# - yes | sdkmanager "platforms;android-29"
# script:
# - ./gradlew build connectedCheck